### ISSUE TITLE
Distributed running instructions

### ISSUE THREAD

**Issue by ypwalter** [Mozilla-TWQA/Hasal#192]
@ShakoHo, @askeing, can you please provide the ways to set up distributed running server and client? I remember that the way to set up client is complex!

**Comment by ShakoHo** [comment]
client?   you mean the setup steps for mitmdump ?  or distributed running?   
if you mean the distributed running, you just need to provide the parameter --online and modify the svrConfig.json  then it should be able to run

**Comment by ypwalter** [comment]
Oh, yes,  mitmdump instructions :P

**Comment by ypwalter** [comment]
@ShakoHo, you can now provide it in wiki.

**Comment by ShakoHo** [comment]
updated
