### ISSUE TITLE
Document how to run one test

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#195]
In my humble opinion, an ideal future state would be:

- we find a big performance difference between Firefox and another browser
- we file a bug including some data and say: "run these steps to reproduce locally"

I haven't gotten things working yet but I *believe* it should be just editing suite.txt?

**Comment by ShakoHo** [comment]
Hi Andrew,

Yes, you can also reference the latest README, I've put some sample command on it.

**Comment by overholt** [comment]
That looks great. Thanks, Shako!






On Tue, Aug 16, 2016 at 5:09 AM -0400, "Shako Ho" <notifications@github.com> wrote:












Hi Andrew,



Yes, you can also reference the latest README, I've put some sample command on it.
