### ISSUE TITLE
Need client_secrets.json?

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#197]
I can't seem to run a test. What am I doing wrong?

<pre>
$ python runtest.py regression suite.txt --max-run=1 --max-retry=1
Set variable name: max_retry with value: 1
Set variable name: advance with value: False
Set variable name: online_config with value: svrConfig.json
Set variable name: keep_browser with value: False
Set variable name: profiler with value: avconv
Set variable name: online with value: False
Set variable name: test_comment with value: <today>
Set variable name: max_run with value: 1
The counter is 0 and the retry counter is 0
========== Environment data ======
{'ENABLE_ADVANCE': '0', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'KEEP_BROWSER': '0', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/overholt', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'UPSTART_EVENTS': 'xsession started', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'XDG_SESSION_TYPE': 'x11', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'overholt', 'USER': 'overholt', 'PATH': '/home/overholt/.hasalenv/bin:/home/overholt/bin:/home/overholt/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '7', 'GNOME_KEYRING_CONTROL': '', 'PS1': '(.hasalenv) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'ONLINE_CONFIG': 'svrConfig.json', 'DISPLAY': ':0', 'PROFILER': 'avconv', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/overholt/.Xauthority', 'LANGUAGE': 'en_US', 'SHLVL': '1', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'QT_ACCESSIBILITY': '1', 'VIRTUAL_ENV': '/home/overholt/.hasalenv', 'UPSTART_INSTANCE': '', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'WINDOWID': '56623114', 'CLUTTER_IM_MODULE': 'xim', 'XMODIFIERS': '@im=ibus', 'HOME': '/home/overholt', 'QT4_IM_MODULE': 'xim', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_SESSION_DESKTOP': 'ubuntu', 'COMPIZ_BIN_PATH': '/usr/bin/', 'XDG_RUNTIME_DIR': '/run/user/1000', 'GTK_IM_MODULE': 'ibus', 'PYTHONPATH': '/usr/local/lib/python2.7/site-packages', 'SESSIONTYPE': 'gnome-session', 'ENABLE_ONLINE': '0', 'VTE_VERSION': '4205', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'UPSTART_JOB': 'unity7', 'NO_GCE_CHECK': 'False', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'XDG_CURRENT_DESKTOP': 'Unity', 'XDG_SESSION_ID': 'c2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-Fhy4CLOARp', '_': '/home/overholt/.hasalenv/bin/python', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'SESSION': 'ubuntu', 'DESKTOP_SESSION': 'ubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/11437', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'GNOME_KEYRING_PID': '', 'OLDPWD': '/home/overholt/opencv/build', 'GDM_LANG': 'en_US', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'INSTANCE': '', 'PWD': '/home/overholt/Hasal', 'JOB': 'unity-settings-daemon', 'GCE_METADATA_TIMEOUT': '3', 'MAX_RUN': '1', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_SEAT': 'seat0'}
========== Environment data ======
python -m unittest tests.test_firefox_gdoc_read_basic_table_1
E
======================================================================
ERROR: test_firefox_gdoc_read_basic_table_1 (tests.test_firefox_gdoc_read_basic_table_1.TestSikuli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_firefox_gdoc_read_basic_table_1.py", line 8, in setUp
    super(TestSikuli, self).setUp()
  File "lib/perfBaseTest.py", line 90, in setUp
    self.target_helper = targetHelper.TagetHelper(self.env)
  File "lib/helper/targetHelper.py", line 6, in __init__
    self.drive_obj = PyDriveUtil()
  File "lib/common/pyDriveUtil.py", line 12, in __init__
    self.gauth = self.get_gauth(settings)
  File "lib/common/pyDriveUtil.py", line 37, in get_gauth
    gauth.LocalWebserverAuth()
  File "/home/overholt/.hasalenv/local/lib/python2.7/site-packages/pydrive/auth.py", line 67, in _decorated
    self.GetFlow()
  File "/home/overholt/.hasalenv/local/lib/python2.7/site-packages/pydrive/auth.py", line 345, in GetFlow
    self.LoadClientConfig()
  File "/home/overholt/.hasalenv/local/lib/python2.7/site-packages/pydrive/auth.py", line 294, in LoadClientConfig
    self.LoadClientConfigFile()
  File "/home/overholt/.hasalenv/local/lib/python2.7/site-packages/pydrive/auth.py", line 314, in LoadClientConfigFile
    raise InvalidConfigError('Invalid client secrets file %s' % error)
InvalidConfigError: Invalid client secrets file ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
[ERROR] test could raise exception during execution!!
##################
# Test Finished! #
##################
</pre>

**Comment by ShakoHo** [comment]
Hi Andrew,
Yes, you are missing some client cert files in your local environment. I will forward to you later.

**Comment by overholt** [comment]
OK we should definitely note that in README.md.

**Comment by ShakoHo** [comment]
Sure, add one step to tell user need to download the client certificate from google drive, and place them in hasal working dir.

**Comment by ShakoHo** [comment]
We already add this notification in bootstrap script. So this issue will be closed.
