### ISSUE TITLE
Can we use a pre-built OpenCV for Ubuntu?

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#198]
Lots of PPAs listed here (not sure which ones we trust): https://launchpad.net/ubuntu/+ppas?name_filter=opencv

**Comment by ShakoHo** [comment]
In ubuntu, we have installed some pre-built opencv before, but they might not support some parameters we needed. That's why we need to install and build the opencv in each environment.

**Comment by overholt** [comment]
If we don't find an existing PPA for OpenCV that works, could we make our own with our own build?

**Comment by ShakoHo** [comment]
add to todo list
