### ISSUE TITLE
Create simple bootstrap.sh

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#199]
Something like Eideticker's would be nice: https://github.com/mozilla/eideticker/blob/master/bootstrap.sh. We can even set it up with Travis like Eideticker has so that it's guaranteed to always work :)

**Comment by ShakoHo** [comment]
maybe we can modify the install_hasal.sh to fulfill this?
@askeing  how do you think?

**Comment by askeing** [comment]
I think it should works, but it may meet some problem.
* `apt-get` will takes the long time
* building `opencv` also have to wait the long time
* `setup sikulix` will have problem, have to skip it on Travis

Ref: https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

**Comment by overholt** [comment]
We could perhaps skirt the timeout issue if we used a pre-build OpenCV (https://github.com/Mozilla-TWQA/Hasal/issues/198).

For sikulix, could we make our own .deb repo or just manually extract the JAR file(s)?

**Comment by askeing** [comment]
@ypwalter , you are more familiar with sikulix, do you have any idea?

**Comment by askeing** [comment]
Currently working on the Mac bootstrap.
It will also run on Travis CI for verifying it works fine.

**Comment by digitarald** [comment]
From what I can tell the issue is fixed, could this be closed?

**Comment by ShakoHo** [comment]
Yes, we should close this one.
