### ISSUE TITLE
Document what options to pick in sikulix installer

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#200]
I see it referenced in lib/common/environment.py but I don't know how to get it. Is it http://sikulix.com/? Is there an alternative to using it?

**Comment by ShakoHo** [comment]
Hi Andrew,
You have to install sikulix from here (https://launchpad.net/sikuli/sikulix/1.1.0) , 
and place the runsikulix and other installtion files in hasal/thirdparty

**Comment by overholt** [comment]
We should document what options one wants to pick in the graphical sikulix installer.

**Comment by ShakoHo** [comment]
Yes, the document is updated.

**Comment by digitarald** [comment]
From what I can tell the issue is fixed, could this be closed?
