### ISSUE TITLE
PYTHONPATH not set by virtualenv (to find OpenCV's shared library)?

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#205]
I can't get things to work (ie. find cv2.so) unless I do the following before executing any of the framework:

<pre>export PYTHONPATH=/usr/local/lib/python2.7/site-package</pre>

**Comment by ShakoHo** [comment]
Hi Andrew,
You need to link the cv2.so in your virtual environment, for example:
cd   ~/.hasalenv/lib/python2.7/site-packages/
ln -s /usr/local/lib/python2.7/site-packages/cv2.so cv2.so

And one more thing, we have a installation script for Ubuntu, located in hasal/install_hasal.sh
You could also reference the script to setup your environment.

**Comment by overholt** [comment]
Ah. https://github.com/Mozilla-TWQA/Hasal/pull/206 :)
