### ISSUE TITLE
Put suite files into one folder, or put into tests folders

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#272]
We will have more and more suite files under Hasal project folder, so I will suggest put them into the same folder, or put them into each tests' folders.

@ShakoHo @MikeLien @ypwalter do you have any idea?

**Comment by MikeLien** [comment]
For organised purpose, I agree for putting them in one folder, either suite folder or tests folder are fine to me.

**Comment by askeing** [comment]
We have https://github.com/Mozilla-TWQA/Hasal/blob/master/tools/generate_suite_file.py now.
`$ python tools/generate_suite_file.py -s tests`
