### ISSUE TITLE
OSX needs python framework build to use matplotlib

### ISSUE THREAD

**Issue by MikeLien** [Mozilla-TWQA/Hasal#290]

**Comment by bobbyc** [comment]
Close?

**Comment by MikeLien** [comment]
This haven't fixed and it's an edge case for current implementation. We use `matplotlib` to plot charts for debugging purpose currently and only OSX has this kind of issue. We already extract this library's usage to [lib/common/matPlot.py](https://github.com/Mozilla-TWQA/Hasal/blob/master/lib/common/matPlot.py) for workaround.
Suggest remain it as known issue and lower its priority until we need to fixed it someday.

**Comment by bobbyc** [comment]
I study IPython and matplotlib environment. This is an issue that IPython doesn't support in virtualenv mode. So you should use it at non-virtual environment instead.
