### ISSUE TITLE
A general video recording format is needed for windows, linux, and mac

### ISSUE THREAD

**Issue by MikeLien** [Mozilla-TWQA/Hasal#291]
We need a general screen recording video format and without additional codec to decode.

**Comment by bobbyc** [comment]
Close?

**Comment by MikeLien** [comment]
Since now video recording format already used [ffmpeg](https://github.com/Mozilla-TWQA/Hasal/blob/master/lib/profiler/avconvProfiler.py#L21-L27) for all platforms. This issue could be closed.
