### ISSUE TITLE
[ffmpeg] PIPE log of screen recording from ffmpeg will lost data

### ISSUE THREAD

**Issue by MikeLien** [Mozilla-TWQA/Hasal#299]

**Comment by MikeLien** [comment]
Using `ffmpeg` codec and PIPE log to file will cause recording problem and get `broken video` and  `incorrect log file`.

**Comment by bobbyc** [comment]
Close?

**Comment by MikeLien** [comment]
Currently we avoid PIPE, instead, we output recording log and redirect stdout & stderr to file handle.
(https://github.com/Mozilla-TWQA/Hasal/blob/master/lib/profiler/avconvProfiler.py#L21-L27)
For not considering resource occupation, suggest wontfix this issue.

**Comment by bobbyc** [comment]
Reopen this if needed.
