### ISSUE TITLE
Allow overriding firefox executable and profile directory

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#370]
When running Hasal on my work machine I want to target it at a specific executable (`--firefox-path`), like Nightly and provide a profile (`--profile-dir`) as well as I have multiple profiles for my Firefox installations.

**Comment by digitarald** [comment]
Adding references for both [setting firefox executable](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Selecting_a_browser_version) and [using profiles](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Using_profiles) in jpm.

**Comment by ypwalter** [comment]
@ShakoHo, I think this should be implemented. Should we?

**Comment by ShakoHo** [comment]
no, we didn't ..it's on the todo list.

**Comment by bobbyc** [comment]
@ypwalter I think this feature was implemented, right? please help to instruct how to use it.

**Comment by ypwalter** [comment]
We haven't implement this specific feature.
It's still on the todo list.

We have alternative ways for setting up a Firefox profiler.
Steps:
1. load https://github.com/Mozilla-TWQA/Hasal/blob/master/settings/default.json with any editor
2. put you desired environmental variables, prefs(about:config settings), and add-ons
3. run Hasal and it will create a new profiler with all the settings you like
