### ISSUE TITLE
suite_bbc_pilot.txt points to c:/ directories, not relative paths

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#372]

**Comment by ypwalter** [comment]
I think that's a old files. We no longer user directory paths

**Comment by digitarald** [comment]
@ypwalter the default suite.txt requires to have the gdocs secrets; maybe something simpler would be nice for first fiddling.

**Comment by ypwalter** [comment]
@digitarald try it with
tests.pilot.bbc.test_firefox_homepage.sikuli
tests.pilot.bbc.test_chrome_homepage.sikuli
should be good.
