### ISSUE TITLE
Topsites revisited

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#380]
Lets track here which topsites need to be added are revisited.

1. **Generic tags/searches**: All things that use `hashtags` or `tags` with `mozilla` (like `https://twitter.com/hashtag/mozilla`) I would rather use a more generic search and something that generates more content, as `mozilla` isn't widely known other than our. I would use more service specific tags, here some shots: `https://twitter.com/hashtag/news`, `https://www.instagram.com/explore/tags/fashion/`

2. **Logins**: `https://mail.google.com/mail/` doesn't work without logins and is also rather complex; could it be removed from the initial set?

**Comment by askeing** [comment]
Hi @digitarald ,
We plan to update the links of `twitter` and `instagram`, but we don't know which key word is suitable for `www.ask.com`.
Do you have any suggestions?

Our links reference list:  https://goo.gl/1av33F
