### ISSUE TITLE
[Perfherder] [PyDrive] Upload video files into Drive's specific folder

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#436]
The Hasal_server doesn't know the `video_path` status of agent, so we have to check the `median time` and `video_path` before upload data to Perfherder.

After having a discussion with @MikeLien , we can upload videos into the specific folder, for example, `<OS>/<TARGET>/<COMMENT>`.
Then we can just upload perf data when we get the `median time` value, and provide the Drive folder's `link` (which contains all video files of this run) into Job Detail tab.

**Comment by askeing** [comment]
@MikeLien any other ideas?

**Comment by MikeLien** [comment]
The video folder structure can be the same as server's one. It looks good to me.
Add @ShakoHo for more input since the original upload video code is designed by you.

**Comment by ShakoHo** [comment]
I will suggest we add a timer on the server side, and skip the video data  when timeout
