### ISSUE TITLE
[Profile] Adding mechanism to create fresh profile for running Firefox

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#444]
Adding mechanism to create fresh profile for running Firefox cases.
And then install useful Add-On. ex: https://github.com/digitarald/perf-marker-webext from @digitarald

**Comment by bobbyc** [comment]
Done and close?

**Comment by ypwalter** [comment]
create fresh profile for running firefox cases was done in #498 by askeing
install useful add-on was done in #513 by me.
