### ISSUE TITLE
SpeedIndex and measuring scrolling in Firefox

### ISSUE THREAD

**Issue by soulgalore** [Mozilla-TWQA/Hasal#468]
Hey! 
Found this repo a couple of days ago, I didn't know you where working a new performance tool at Mozilla. I've been able to test it out yet (does it work) but I'm really interested. Part of Hasal I think (but not sure) is the same thing as we do in https://github.com/sitespeedio/browsertime (starting the browser, record the screen, use Visual Metrics to collect SpeedIndex and related metrics). I think maybe you can use parts or at least use it as inspiration. It works.

But you also wanna automate scrolling performance right (seen you have tests for Wikipedia). I would love to learn more about how you do that with Firefox and if that is something we can use in the Wikimedia performance team (today we only measuring SpeedIndex and other data from WebPageTest and Navigation Timings and related from RUM) but it would be super cool to have a good way of automated measuring scroll performance in Firefox.

For sitespeed.io/Browsertime related stuff you can reach me at peter [at] soulgalore [dot] com and for scrolling and measuring Wikipedia, you can reach me at peter [at] wikimedia [dot] org :)

Really interesting project and would love to try it out!

**Comment by digitarald** [comment]
@soulgalore @MikeLien has some experimental measures for scroll performance. They work great with the old non-asynchronous scrolling as they measure dropped frames by converting frame differences into a waveform. The measure has to evolve to capture checkerboarding, as that is the visual artifact that happens in Chrome/Firefox with compositor based scrolling.

I filed https://github.com/Mozilla-TWQA/Hasal/issues/518 to follow up.

**Comment by bobbyc** [comment]
Close and follow in #518
