### ISSUE TITLE
 Ensure Hasal test configuration is using recommend benchmarking settings

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#493]
This was filed in Mozilla Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1328949

**Comment by askeing** [comment]
Stage 1 finished.
Currently it works for running `--firefox-settings settings/default.json`, and profiling`--firefox-settings settings/default.json --profiler=geckoprofiler`.
For running, it will create a new Firefox profile with `prefs` and `cookies` you want. And then running with `env`.
For profiling, it still is temporary solution. It will put the `prefs` and `cookies` into unzipped profile folder (from `resource/*.zip`). And then running with `env`.

Stage 2 will change the mechanism for installing XPI (addons, extensions), and enabling profiler.
