### ISSUE TITLE
Use same virtual environment name? <all>

### ISSUE THREAD

**Issue by bobbyc** [Mozilla-TWQA/Hasal#516]
I found Linux and Mac used .env-python as virtual env name, but Windows use Hasal-env. Could we rename as same name to let people has same user experience on all platform?

**Comment by ypwalter** [comment]
finished modified accordingly

**Comment by bobbyc** [comment]
what is final decision of name? or please attach pull request in issue. thanks.

**Comment by ypwalter** [comment]
https://github.com/Mozilla-TWQA/Hasal/commit/f742eb094b3477b0cd9ddca8086c3f1a35811103

env-python
