### ISSUE TITLE
Separate test suites from framework repo

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#517]
Test suites should be maintained in another repo (`hasal-suites`). This repo could still include an example test case as a *hello world*.

Goal here is to make it easier to track work and to contribute by compartmentalizing it.

Would love to hear thoughts on any downsides or alternatives I missed.

**Comment by bobbyc** [comment]
I can see the benefit to contribute cases from participants, and make framework clear. No big concern from me. @ShakoHo?

**Comment by ShakoHo** [comment]
Hi Harald, 
Yes, I agree the separated repo could bring some benefit on tracking issues and controlling the specific PR for test cases.

However, to separate the repo could also bring some overhead of our current development flow and management effort and version compatibility issue between repos.

I will not say this is not the way we should go, but maybe right now is the best time to do it?

**Comment by digitarald** [comment]
Yes Shako, definetely not a priority. Conference season starts in Summer for Dominik and me, where we start blasting out the news about Hasal 📢 .

**Comment by bobbyc** [comment]
Not today. Please recall this if you need in the future.
