### ISSUE TITLE
[Meta] Breakdown interaction metrics

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#522]
Right now we benchmark each test by `run time`, which is based on observing the tab throbber for page load tests.

For clarity, run time is important and our current key metric. The next step we need is to get more diagnostic metrics for each run on different aspects of perceived performance. The new metrics will help diagnosis and tracking improvements but eventually will also lead to key metrics that are more correlated to perception.

✏️  **Strawman** ✏️ 

# Page Load

Currently covered *first non-blank paint* and *(Perceptual) Speed Index*.

# Responsiveness

Break down interactions. [RAIL](https://developers.google.com/web/fundamentals/performance/rail) can guide us here.

## Input Latency

Input to first paint. See #547.

# Smoothness

## Scrolling

See #518

## Animation

Ratio of dropped frame during animation.

**Comment by bobbyc** [comment]
@digitarald, please help to confirm that first non-blank paint and SI/PSI will be covered by WPT. Thanks.

**Comment by bobbyc** [comment]
Close this issue as done MVP
