### ISSUE TITLE
Switch from Projects for tracking Work and Backlog

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#534]
https://help.github.com/articles/about-projects/

Making it easier to track what's being worked outside of the spreadsheet and have discussions to is as well.

Thoughts, @bobbyc ?

**Comment by bobbyc** [comment]
As Hasal weekly meeting, we would like to defer this topic in short term.

**Comment by bobbyc** [comment]
Hasal team still use the spreadsheet to manage daily work. However, we manage measurement requests and issue on Github to balance project management.
