### ISSUE TITLE
Cannot launch Chrome cases due to #537

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#540]
ref: #537 

- `windows_language_postfix ` and `ubuntu_language_prefix ` have to add `self.`.
- For `self.launch_cmd = [ubuntu_language_prefix] + self.launch_cmd`, it should add into `self.test_env` [1].

[1] https://github.com/Mozilla-TWQA/Hasal/blob/master/lib/browser/base.py#L30

**Comment by ypwalter** [comment]
https://github.com/Mozilla-TWQA/Hasal/pull/541
