### ISSUE TITLE
Input Latency MVP

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#547]
Measure time from input to screen updated.

@MikeLien, can you fill in the details on what is planned?

**Comment by MikeLien** [comment]
Currently the initial plan is to integrate prototyping case in Hasal framework.
There have some tasks need to be finished in this integration.
- [ ] Add trigger point for input latency of typing case
- [ ] Switch test type to give other indexes
- [ ] Modify analysis code
- [ ] Add specific typing case

**Comment by digitarald** [comment]
@MikeLien can you confirm that this will not only cover typing but any interaction, like clicking a button, focusing a field, etc?

**Comment by MikeLien** [comment]
For getting whole period from input event to display shown, we propose a new solution to get input latency.

1. Snapshot before input command
2. Input event with log
3. Snapshot after display shown

This solution can apply to not only typing case but all interactions with log in console.
- For clicking a button, the latency would be from clicking command shown on console until button display change.
- For focusing a field, the latency would be from focus action/command shown on console until the field is focused and display changed.

**Comment by bobbyc** [comment]
Detail definition of Actual input latency in [Google Docs](https://docs.google.com/document/d/1nZZmcXbbuXRt0ilXTs7c1CPYdiH1bb6kp2Zk8FtywgY/edit)

**Comment by bobbyc** [comment]
Per Mike's test:

Below are experimental results for input latency of clicking from https://codepen.io/digitarald/pen/gmwyde 

Chrome: 752.81 ms
Generated result GIF file for 10 times slower from input event log to website display change: https://drive.google.com/a/mozilla.com/file/d/0B9Zi9TqbRWsdOGV5Sm4xWGZ6a0xabWpLLTZNMVFhR0dRNFZJ/view?usp=sharing

Firefox: 764.04 ms
Generated result GIF file for 10 times slower from input event log to website display change: https://drive.google.com/open?id=0B9Zi9TqbRWsdZWs0VHFYS2VST2dTQ0tTeDFzOHRjdnNuQWZz

**Comment by digitarald** [comment]
@MikeLien what are the numbers reported in the script on the page to compare with? They are not visible in the loop. ~750ms seems way too high, I expect between 30-60ms.

**Comment by digitarald** [comment]
This link opens full screen without iframes: https://s.codepen.io/digitarald/debug/gmwyde/VGrWNnNyoyNM

**Comment by bobbyc** [comment]
@digitarald your latest codepen link is not working.

**Comment by MikeLien** [comment]
I think the correct link might be https://codepen.io/digitarald/full/gmwyde, @digitarald if I'm wrong, please correct me.
Harald, thanks for your comment and reminder. I review the whole case and steps again and there are some findings. Detailed information please refer to #561.
The input latency of click case is similar with AIL case but there are several tricky points. The ~750ms came from the combination of original case design and webapp behavior.

First, the web page you provide only reflect on screen after a pair of mouse down and mouse up events (combination of click behavior).
Second, the sikuli command we sent in the original case is a `click()` command but it combines find target, mouse down, mouse up actions.

After this finding, I redesign the test case to take `mouse up` as start point and the result would be around 33ms. You can refer to https://drive.google.com/open?id=0BwkEhia_D6l_cmV4R0VZUXdEMFE and see the latest results.

The following questions are, what start points(`mouse down` or `mouse up`) would we use for different webapps, my assumption is it would be case by case since some webapps might reflect while receiving `mouse down` event. And if webapp such as yours only reflect after `mouse up`, we can skip the time cost of `mouse down`.

Any thought?

**Comment by bobbyc** [comment]
A rough analysis of GDocs input latency from Mike's prototype in last week.

https://gist.github.com/bobbyc/dc92db9e063b99ff73b21846936e359e

**Comment by digitarald** [comment]
@MikeLien the new number looks much closer to reality.

> The following questions are, what start points(mouse down or mouse up) would we use for different webapps, my assumption is it would be case by case since some webapps might reflect while receiving mouse down event.

Case by case to get a close to what sites themselves would report. Clicks are only fired on mouse up, so we should not expect anything earlier.

@bobbyc looks good. I would strive for 2 tests in google docs and it looks like we have half-way there. These are not continues reported numbers but just an exercise to baseline. When Quantum Flow engineers pick up those numbers to optimize against, only then they should be fed into perfherder.

1. typing into google doc (empty for now to test the easiest case)
  - Follow up would be testing in a 10-page doc like our meetings notes to see how much #-of-pages matters
2. editing a cell in google sheets (again, empty to simplify)
  - Follow up again with a heavier sheet

**Comment by digitarald** [comment]
@bobbyc @MikeLien any update on my latest comment?

**Comment by MikeLien** [comment]
We already done integrated work from yesterday and with a gdoc case of typing one character on #562.

**Comment by bobbyc** [comment]
@digitarald As mike's comment, the MVP just integrated to the repo. So our team members could start to extend MVP to others scenarios. We expect extending MVP to 10-pages for GDocs and GSheets, and single run by Today. And try to have more runs by Wednesday.

**Comment by bobbyc** [comment]
> 1. typing into google doc (empty for now to test the easiest case)
>  - Follow up would be testing in a 10-page doc like our meetings notes to see how much #-of-pages matters

Report: https://gist.github.com/bobbyc/239d45c74f5bf3826aad153e60daf862

>2. editing a cell in google sheets (again, empty to simplify)
 > - Follow up again with a heavier sheet

Report: https://gist.github.com/bobbyc/1b259bec035679ccabc1388d05ede149

**Comment by digitarald** [comment]
@bobbyc thanks for the notebook, the analysis really helps to understand and validate the data.

> Report: https://gist.github.com/bobbyc/239d45c74f5bf3826aad153e60daf862

The Firefox/Chrome ratio look as expected.

@MikeLien it looks like the times reported fall into buckets (50.000000, 66.666667, 83.333333, 100.000000, 116.666667). Do you have an hypothesis on why that would be?

>  Report: https://gist.github.com/bobbyc/1b259bec035679ccabc1388d05ede149

I expected Firefox to be much worse in this one. Did you check the videos on if there might be a lag in characters appeared either in the edited field or the edit field on top of the sheet?

**Comment by MikeLien** [comment]
> it looks like the times reported fall into buckets (50.000000, 66.666667, 83.333333, 100.000000, 116.666667). Do you have an hypothesis on why that would be?

These values comes from screen capture with 60fps setting and represent the period from log appear until character shown on screen is 3, 4, 5, 6, or 7 frames, respectively.
There might be many possible variables to cause this variation, e.g., system status, network status, or browser status, etc.

**Comment by bobbyc** [comment]
@digitarald @jeanygong

Keyboard pagedown input latency in GDocs and GSheets:
https://gist.github.com/bobbyc/faa7f45c280def03a434763071c48745

**Comment by digitarald** [comment]
> These values come from screen captured video analysis with 60fps setting and represent the period from log appear until character shown on screen are 3, 4, 5, 6, or 7 frames, respectively.

Looks like the measure is so coarse that is basically gives us input latency as `number of frames `; which might be actually OK as that maps how the event queue works.

@MikeLien have we tried FPS > 60?

**Comment by bobbyc** [comment]
@digitarald as our discussion, Gecko produces frames along Vsync (60hz). So it doesn't make sense we capture screens over 60fps. Of course in high-performance hardware with a Graphic card and display device, we could setup refresh rates > 60hz, 90hz, or even 120hz. Then we could adjust capture screen rate as well. 

@MikeLien correct me if I'm wrong. However, you did 90hz capture rate before; we could try it few times to valid number against capture rate 60. Thanks.

**Comment by MikeLien** [comment]
@digitarald as Bobby said, for vsync alignment we choose 60fps as screen capture's setting and due to the measurement period from log shown to character shown, the overhead's upper bound will be one time result value plus one video frame's duration.
We still can try to compare results between 60fps and 90fps settings and see if their distribution is similar or not.

**Comment by cpeterso** [comment]
> Gecko produces frames along Vsync (60hz). So it doesn't make sense we capture screens over 60fps.

Is the screen capture software also vsync-aligned, capturing Gecko frames on the same millisecond they are drawn? If not, then we might need to oversample at 120 fps to account for the [Nyquist rate](https://en.wikipedia.org/wiki/Oversampling) when sampling a 60 fps input signal.

**Comment by bobbyc** [comment]
> Is the screen capture software also vsync-aligned, capturing Gecko frames on the same millisecond they are drawn? If not, then we might need to oversample at 120 fps to account for the Nyquist rate when sampling a 60 fps input signal.

@MikeLien Looks like your original approach, 90 fps sampling rate, is right and make sense from the digital processing perspective. Sorry for my non-expert opinions. Please help to understand what is the max oversampling rate we could reach in our lab hardware.

@cpeterso good point from the Nyquist rate.

**Comment by bobbyc** [comment]
Done and close. Please reopen if you have more question. thanks.
