### ISSUE TITLE
Scroll Checkerboarding

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#552]
Spin off from #518

Open Firefox to see recordings/replays of your own checkerboarding logs: `about:checkerboard`

To kick things off Hasal should collect a histogram of checkerboarding durations and peak of area affected.

End goal would be to map Firefox's telemetry implementation for [CHECKERBOARDING_SEVERITY](https://bugzilla.mozilla.org/show_bug.cgi?id=1238040).

**Comment by digitarald** [comment]
@bobbyc Jean mentioned that we might get this metric by the work week; can you give a status here?

**Comment by bobbyc** [comment]
@digitarald No, we are not working on this yet. As conversation last week, we will only focus on AIL and FT before the work week.

**Comment by jeanygong** [comment]
My mistake.  This is not a deliverable for TOR work week Mar 27.

**Comment by bobbyc** [comment]
From gecko source code:

const char* CheckerboardEvent::sColors[] = {
"brown",
"darkgreen",
"lightgreen",
"yellow",
"red",
};


enum RendertraceProperty {
Page,
PaintedCriticalDisplayPort,
PaintedDisplayPort,
RequestedDisplayPort,
UserVisible,

// sentinel final value
MAX_RendertraceProperty
};

**Comment by bobbyc** [comment]
As Andreas's message, checkerboarding only for diagnostic perspective. It's not as release criteria perspective for release 57. 

Leave this as backlog here, please revisit if we got more information.
