### ISSUE TITLE
[Sikuli] Delay and Scan Rate Settings

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#561]
I found the Sikuli has some delay settings:
- `Settings.MoveMouseDelay`
- `Settings.DelayValue`
- `Settings.DelayBeforeMouseDown`
- `Settings.ClickDelay`
- `Settings.TypeDelay`
and two scan rate settings (FPS):
- `Settings.WaitScanRate`
- `Settings.ObserveScanRate`

These settings might help us.
@MikeLien , after set `Settings.MoveMouseDelay` to 0, the `click()` will speed up from `0.73 sec` to `0.22~0.23 sec`.

Ref:
- https://github.com/RaiMan/SikuliX-2014/blob/master/API/src/main/java/org/sikuli/basics/Settings.java
- http://sikulix-2014.readthedocs.io/en/latest/scripting.html#Settings

**Comment by askeing** [comment]
Before change `Settings.MoveMouseDelay`:
- `click` take 0.72000002861 sec
- `mouseDown` & `mouseUp` take 0.22000002861 sec
- `mouseDown` take 0.209999799728 sec
- `mouseUp` take 0.00999999046326 sec

After change `Settings.MoveMouseDelay` to 0:
- `click` take 0.22000002861 sec
- `mouseDown` & `mouseUp` take 0.22000002861 sec
- `mouseDown` take 0.210000038147 sec
- `mouseUp` take 0.00999999046326 sec

**Comment by digitarald** [comment]
@askeing do `WaitScanRate` and `ObserveScanRate` affect any commands used by Hasal? Seems to only affect `Region.wait(), Region.exists(), Region.waitVanish(), Region.observe()`

**Comment by MikeLien** [comment]
@digitarald Sorry for late reply, these settings don't affect Hasal's test. We wait or check objects are shown or not in a test but that won't make final result any difference. Only recently new cases related to input latency which needs to consider sikuli's command's overhead thus we dive into these sikuli's settings then make sure we can get precisely values.
