### ISSUE TITLE
Incorrect replace '.' as os seperation on windows 10

### ISSUE THREAD

**Issue by bobbyc** [Mozilla-TWQA/Hasal#563]
Replacing bug in https://github.com/Mozilla-TWQA/Hasal/blob/master/runtest.py#L262
`
                    else:
                        test_case_fp = test_case.replace(".", os.sep) + ".py"
                        test_name = test_case.split(".")[-1]
                        case_data[test_case]["TEST_SCRIPT_PY_DIR_PATH"] = os.sep.join(test_case.split(".")[:-1])
                        if os.path.exists(test_case_fp):
                            test_case_module_name = test_case
                            test_env = self.get_test_env(**case_data[test_case])
`

Actual Result:
Place tests\test_firefox_timing.sikuli\ in suite.txt. Runtest.py will repalce suitename as tests\\test_firefox_timing\sikuli\\.

Please fix the bug.

**Comment by bobbyc** [comment]
test

**Comment by bobbyc** [comment]
ack

**Comment by ShakoHo** [comment]
tests\test_firefox_timing.sikuli is NOT a test case, so you suppose should not run it as an individual test case, if you want to generate the suite file please use the generate_suite_file.py in tools and if you have any question about using this tool, please come to lab, we are happy to share the knowledge with you.
