### ISSUE TITLE
Client certificate without mozilla.com account?

### ISSUE THREAD

**Issue by soulgalore** [Mozilla-TWQA/Hasal#601]
Hey! I wanted to try out Hasal but got stuck on:

> Download the client certificate from here (https://goo.gl/yfki48 -- note: needs a mozilla.com account ATM), place all certificates in your hasal working dir.

Any chance there can be a fix so Hasal is open to try without an mozilla.com account?

Thanks
Peter

**Comment by digitarald** [comment]
cc @ShakoHo 

I think this is only needed for the google docs tests Hasal was running. Is it working without?

**Comment by ShakoHo** [comment]
Yes, the framework is able to run without the client certificate.
But without the client certificate, you are not able to run the case of Gsuite and Facebook.
I will implement a fix to ignore client certificate, but a user might only run the top site test cases without the client certificate.

**Comment by ShakoHo** [comment]
#654

**Comment by bobbyc** [comment]
@soulgalore  Peter, Shako updated this. Please let us know if you have more question. thanks.
