### ISSUE TITLE
Facebook cases can not execute

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#722]
@ShakoHo found there is no defined `similarity`.
https://github.com/Mozilla-TWQA/Hasal/blob/dev/lib/sikuli/facebook.sikuli/facebook.py#L63

**Comment by askeing** [comment]
This code comes from https://github.com/Mozilla-TWQA/Hasal/commit/b4c45da8750ffb926f428d64d29a1252088631c6

@ypwalter could you help to submit a PR to identify the default `similarity`?
Thank you.

**Comment by askeing** [comment]
After having a quick discussion with @ypwalter , the default value should be `0.7`.
I will help to submit patch in PR #718

**Comment by ShakoHo** [comment]
and also missing image file [facebook_messenger_header_win10.png] in repo

**Comment by ShakoHo** [comment]
test_chrome_facebook_ail_scroll_home_1_txt
test_chrome_facebook_ail_type_message_1_txt
test_firefox_facebook_ail_type_message_1_txt 
these 3 cases are affected.

**Comment by askeing** [comment]
@ypwalter could you please help to fix it, and then verify the Facebook cases above again?
