### ISSUE TITLE
Use pyup.io to keep Python dependencies up to date

### ISSUE THREAD

**Issue by edmorley** [Mozilla-TWQA/Hasal#862]
Several Mozilla projects now use https://pyup.io/ to automatically open PRs when their Python packages have new releases available. Perhaps it's a good fit for this project too?

(Context: keeping the treeherder-client package up to date to help the Treeherder team deprecate API features more expediently)

**Comment by ShakoHo** [comment]
Done, we set the pyup to monitor the dev branch, and we will check is there any insecure package in our requirements.txt

**Comment by edmorley** [comment]
Great! However I notice that the auto-PR feature is only enabled for insecure updates and not all updates. For us that was one of the big advantages of the tool, so I'd recommend doing that at some point too.

(treeherder-client is still out of date)
