### ISSUE TITLE
Treeherder issue: code 403

### ISSUE THREAD

**Issue by ypwalter** [Mozilla-TWQA/Hasal#882]
#876 would fail in some newly installed machine. Still need to figure out the reasons.

**Comment by askeing** [comment]
submit fix
https://github.com/Mozilla-TWQA/Hasal/pull/876/commits/f21788ae15ff32c7d9eb47bbca02a255335ef319

**Comment by askeing** [comment]
After doing some analysis, 2nd `403` issue should be timestamp issue.
The Hawk client will generates the `nonce` and a `timestamp`, using them to interaction with the server.

We should change the Failed PC's NTP to alive server.

**Comment by askeing** [comment]
@ShakoHo @MikeLien @ypwalter @MarkYan 
It seems like we can close this issue due to we found the two reasons and solutions of submitting data to Treeherder.
