### ISSUE TITLE
config firefox default.json "launch-browser-cmd-path" overwrite firefox path from bootstrap

### ISSUE THREAD

**Issue by zapion** [Mozilla-TWQA/Hasal#941]
#819 changed run-firefox path
I tried to trace and found many places could possibly affect.
Likewise, bootstrap.bat makes symbolic link to to some possible firefox home dir, which takes no effect after this config exists.

Suggest to have a central config set-get pool class so that everything can be handled properly.
@askeing might have more thought.

**Comment by askeing** [comment]
In my opinion, maybe we can add two options `--fx-bin` and `--ch-bin` (ch?cr?gc?) for binaries file path, and one argument for case suite file path.

ex: `python runtest.py --exec-config ... --index-config ... --fix-bin <PATH/TO/FX> --ch-bin <PATH/TO/CH> <PATH/TO/SUITE_FILE>`
