### ISSUE TITLE
Update treeherder-client from 3.1.0 to 4.0.0

### ISSUE THREAD

**Issue by edmorley** [Mozilla-TWQA/Hasal#951]
Please can you update [treeherder-client](https://pypi.python.org/pypi/treeherder-client) to the latest release (4.0.0) to pick up changes to which API endpoints are used (the old endpoints will be disabled at some point in the future):
https://github.com/Mozilla-TWQA/Hasal/blob/ea4bcad4371230f8fa98c0834c37e1add9ef5816/tools/requirements.txt#L1
https://github.com/Mozilla-TWQA/Hasal/blob/44c58ec873b1f388dfa3050957a876fdcae92730/requirements.txt#L15

The changelog can be found here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1387711#c2

Many thanks!

**Comment by edmorley** [comment]
Many thanks :-)

**Comment by askeing** [comment]
@edmorley No problem :)
